// RunnerBarUITests.swift
// RunnerBarUITests
//
// XCUIApplication-based UI smoke tests.
// Runs on the self-hosted runner via xcodebuild (not swift test).
// The ephemeral .xcodeproj is generated by XcodeGen from project.yml at CI time.
//
// ⚠️ This app uses NSPanel (not NSPopover).
//    Use app.windows.firstMatch — NEVER app.popovers.firstMatch.
// ⚠️ UI_TESTING=1 is injected via launchEnvironment, which causes the app to
//    skip RunnerStore.shared.start() and all keychain/network access.

import XCTest

final class RunnerBarUITests: XCTestCase {

    var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication()
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launch()
    }

    override func tearDown() {
        app.terminate()
        super.tearDown()
    }

    /// Verifies the app process starts and reaches the running state without crashing.
    func testAppLaunchesWithoutCrashing() {
        XCTAssertTrue(app.wait(for: .runningForeground, timeout: 5))
    }

    /// Verifies the NSStatusItem is present in the menu bar after launch.
    func testStatusBarItemExists() {
        let statusItem = app.statusItems.firstMatch
        XCTAssertTrue(statusItem.waitForExistence(timeout: 3))
    }

    /// Verifies clicking the status item shows the NSPanel.
    /// ⚠️ App uses NSPanel (borderless, non-activating) — query via app.windows, not app.popovers.
    func testPanelOpensOnClick() {
        let statusItem = app.statusItems.firstMatch
        guard statusItem.waitForExistence(timeout: 3) else {
            XCTFail("Status item not found in menu bar")
            return
        }
        statusItem.click()
        let panel = app.windows.firstMatch
        XCTAssertTrue(panel.waitForExistence(timeout: 3))
    }
}
