// RunnerBarUITests.swift
// RunnerBarUITests
//
// Passive AX smoke tests — no mouse movement, no window focus stealing.
// Runs on the self-hosted runner via xcodebuild.
// The ephemeral .xcodeproj is generated by XcodeGen from project.yml at CI time.
//
// Design constraints:
//   • XCUIApplication on macOS is NOT headless — any click/type moves the real
//     mouse cursor and steals focus on the active desktop session.
//   • All tests here are READ-ONLY: they only query the AX tree, never synthesise
//     input events. This keeps CI safe to run on a shared/active machine.
//   • Interactive tests (click → panel opens) belong in a local dev scheme only,
//     or must run in an isolated user session via fast-user-switching.
//
// ⚠️ LSUIElement apps never reach .runningForeground — use .runningBackground.
// ⚠️ This app uses NSPanel, not NSPopover — use app.windows, not app.popovers.

import XCTest

final class RunnerBarUITests: XCTestCase {

    var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication()
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launch()
    }

    override func tearDown() {
        app.terminate()
        super.tearDown()
    }

    /// App process reaches running state without crashing.
    /// LSUIElement agents run in the background, never .runningForeground.
    func testAppLaunchesWithoutCrashing() {
        XCTAssertTrue(
            app.wait(for: .runningBackground, timeout: 5),
            "App should reach .runningBackground (LSUIElement agent — never .runningForeground)"
        )
    }

    /// NSStatusItem is present in the menu bar AX tree after launch.
    /// Read-only AX query — no mouse movement.
    func testStatusBarItemExists() {
        XCTAssertTrue(
            app.statusItems.firstMatch.waitForExistence(timeout: 3),
            "Status bar item should be visible in the AX tree"
        )
    }
}
