// RunnerBarUITests.swift
// RunnerBarUITests
//
// Passive AX smoke tests — no mouse movement, no window focus stealing.
// Runs on the self-hosted runner via xcodebuild.
// The ephemeral .xcodeproj is generated by XcodeGen from project.yml at CI time.
//
// Design constraints:
//   • XCUIApplication on macOS is NOT headless — any click/type moves the real
//     mouse cursor and steals focus on the active desktop session.
//   • All tests here are READ-ONLY: they only query the AX tree, never synthesise
//     input events. This keeps CI safe to run on a shared/active machine.
//
// WHY app.windows IS EMPTY FOR THIS APP:
//   RunnerBar is an LSUIElement background agent (sandboxed). XCTest's AX server
//   scopes app.windows to the process handle, which returns empty for LSUIElement
//   agents. setActivationPolicy(.regular) is also blocked by the sandbox —
//   the call silently does nothing, so .runningForeground is never reached.
//   XCUIScreen.main.windows is the only reliable way to get the panel window.
//   See UITEST-LESSONS.md for the full investigation.
//
// ⚠️ XCUIApplication must be initialised with the bundle ID (not default init)
//    to avoid Xcode 26 path resolution bug with LSUIElement apps.
// ⚠️ Do NOT set XCTTargetAppPath in project.yml scheme env — Xcode 26 strips
//    the .app extension, causing a fatal "bundle ID couldn't be read" error.
// ⚠️ To open the panel in CI (no mouse available), set OPEN_PANEL_ON_LAUNCH=1
//    in launchEnvironment. The app positions the panel with setFrameOrigin+orderFront
//    (NOT openPanel() — that requires a real status item position).

import XCTest

final class RunnerBarUITests: XCTestCase {

    var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        // Use explicit bundle ID — avoids XCTTargetAppPath .app-extension stripping
        // bug on macOS 26 with LSUIElement apps.
        app = XCUIApplication(bundleIdentifier: "dev.eonist.runnerbar")
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launch()
    }

    override func tearDown() {
        app.terminate()
        super.tearDown()
    }

    // MARK: - Smoke tests (no panel required)

    /// App process reaches running state without crashing.
    /// LSUIElement agents always land in .runningBackground — never .runningForeground.
    func testAppLaunchesWithoutCrashing() {
        XCTAssertTrue(
            app.wait(for: .runningBackground, timeout: 5),
            "App should reach .runningBackground (LSUIElement agent never reaches .runningForeground)"
        )
    }

    /// NSStatusItem is present in the menu bar AX tree after launch.
    /// Read-only AX query — no mouse movement.
    func testStatusBarItemExists() {
        XCTAssertTrue(
            app.statusItems.firstMatch.waitForExistence(timeout: 3),
            "Status bar item should be visible in the AX tree"
        )
    }

    // MARK: - Panel UI test (real UI, no mouse click)

    /// The panel window appears and contains the expected header elements.
    ///
    /// Uses `OPEN_PANEL_ON_LAUNCH` env var to trigger panel display inside
    /// the app 300ms after launch — no mouse click needed, cursor stays still.
    ///
    /// Uses XCUIScreen.main.windows instead of app.windows because RunnerBar is
    /// a sandboxed LSUIElement agent: app.windows is always empty for such processes
    /// and setActivationPolicy(.regular) is blocked by the sandbox.
    func testPanelOpensAndShowsWorkflowsSection() {
        // Re-launch with the auto-open flag.
        app.terminate()
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launchEnvironment["OPEN_PANEL_ON_LAUNCH"] = "1"
        app.launch()

        // LSUIElement agents land in .runningBackground.
        XCTAssertTrue(
            app.wait(for: .runningBackground, timeout: 5),
            "App should reach .runningBackground before panel check"
        )

        // app.windows is always empty for sandboxed LSUIElement processes.
        // XCUIScreen.main.windows grabs all visible windows — the panel is the
        // only window on screen (positioned top-right by setFrameOrigin), so
        // firstMatch is unambiguous.
        let panel = XCUIScreen.main.windows().firstMatch
        XCTAssertTrue(
            panel.waitForExistence(timeout: 10),
            "Panel (NSPanel) should appear via XCUIScreen.main.windows after auto-open"
        )

        // The panel's SwiftUI content always renders a 'Workflows' static text
        // regardless of auth state — it is the section header in PanelMainView.
        let workflowsHeader = app.staticTexts["Workflows"]
        XCTAssertTrue(
            workflowsHeader.waitForExistence(timeout: 5),
            "Panel content should contain the 'Workflows' section header"
        )
    }
}
